spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.65.12:1521:ibsdb
    driverClassName: oracle.jdbc.OracleDriver
    username: elvin
    password: test
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.Oracle12cDialect
    properties:
      hibernate:
        show_sql: true
    generate-ddl: true
  application:
    name: Beginner project
server:
  port: 8080
